-- settings for Exotic Industries

data:extend({
  {
      name = "ei-tech-scaling-maxCost",
      type = "string-setting",
      setting_type = "startup",
      default_value = "Default",
      allowed_values = {"Default", "Very Cheap", "Cheap", "Expensive", "Very Expensive"},
      order  = "a1",
  },
  {
      name = "ei-tech-scaling-startPrice",
      type = "int-setting",
      setting_type = "startup",
      default_value = 10,
      minimum_value = 1,
      maximum_value = 10000,
      order  = "a2",
  },
  {
      name = "ei-tech-scaling-additionalMultiplier",
      type = "int-setting",
      setting_type = "startup",
      default_value = 1,
      minimum_value = 1,
      maximum_value = 100,
      order  = "a2-1",
  },
  {
      name = "ei-tech-scaling-curveForm",
      type = "string-setting",
      setting_type = "startup",
      default_value = "linear",
      allowed_values = {"linear", "quadratic", "exponential"},
      order  = "a3",
  },
  {
      name = "ei-pipe-to-ground-length",
      type = "int-setting",
      setting_type = "startup",
      default_value = 20,
      minimum_value = 10,
      maximum_value = 40,
      order  = "a5",
  },
  {
      name = "ei-nuclear-reactor-energy-output",
      type = "string-setting",
      setting_type = "startup",
      default_value = "200MW",
      allowed_values = {"75MW", "150MW", "200MW", "225MW", "300MW"},
      order  = "a6",
  },
  {
      name = "ei-nuclear-reactor-remove-bonus",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "a7",
  },
  {
      name = "ei-barrel-capacity",
      type = "int-setting",
      setting_type = "startup",
      default_value = 1000,
      minimum_value = 50,
      maximum_value = 5000,
      order  = "a8",
  },
  {
      name = "ei-loader-prototype-complexity",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "a9",
  },
  {
      name = "ei-rocket-lift-capacity-buff",
      type = "int-setting",
      setting_type = "startup",
      default_value = 0,
      minimum_value = 0,
      maximum_value = 20,
      order  = "a10",
  },
  {
      name = "ei-beacon-overload",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "b1",
  },
  {
      name = "ei-max_updates_per_tick",
      type = "int-setting",
      setting_type = "startup",
      default_value = 10,
      minimum_value = 1,
      maximum_value = 100,
      order  = "b5",
  },
  {
      name = "ei_ticks_per_full_update",
      type = "int-setting",
      setting_type = "startup",
      default_value = 60,
      minimum_value = 8, --At least 1 tick per entity updater type
      maximum_value = 6000,
      order  = "b6",
  },
  {
      name = "ei-expanded-gui",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "c1",
  },
  {
      name = "ei-tech-tree-flatten",
      type = "bool-setting",
      setting_type = "startup",
      default_value = false,
      order  = "c1",
  },
  {
      name = "ei-no-triggers",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "c1",
  },
  {
      name = "ei-no-tech-scaling",
      type = "bool-setting",
      setting_type = "startup",
      default_value = false,
      order  = "c1",
  },
})

data:extend({
{
    name = "ei_fueler_max_updates_per_tick",
    type = "int-setting",
    setting_type = "startup",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 100,
    order  = "d1",
    hidden = true
},
{
    name = "ei_fueler_range",
    type = "int-setting",
    setting_type = "startup",
    default_value = 20,
    minimum_value = 1,
    maximum_value = 100,
    order  = "d2",
},
})

data:extend({
{
    name = "ei_trains_max_updates_per_tick",
    type = "int-setting",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 100,
    order  = "e1",
    hidden = true
},
})